name: Build and Deploy Site

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Update publication dates
        run: python python_scripts/update_dates.py

      # --- LISÄTTY UUSI VAIHE TÄHÄN ---
      - name: Run glossary autotagger
        run: python python_scripts/autotag_glossary.py

      # --- TÄTÄ VAIHETTA ON MUOKATTU ---
      - name: Commit and push automated changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          # Muokattu commit-viesti kattamaan molemmat muutokset
          git diff-index --quiet HEAD || git commit -m "Automated: Update dates and glossary tags [ci skip]"
          git push

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
